return {
  { "folke/which-key.nvim", enabled = false },
  { "folke/trouble.nvim", enabled = false },
  { "catppuccin", enabled = false },
  { "grug-far.nvim", enabled = false },
  { "luvit-meta", enabled = false },
  { "dashboard-nvim", enabled = false },
  { "cmp-git", enabled = false },
  { "cmp-path", enabled = false },
  { "cmp-buffer", enabled = false },
  { "folke/todo-comments.nvim", enabled = false },
  { "folke/persistence.nvim", enabled = false },
  { "folke/flash.nvim", enabled = false },
  { "indent-blankline.nvim", enabled = false },
}
